id: P006692
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3569
  title: དཀྱིལ་འཁོར་གྱི་ཐིག་རྩ་དང་དྲི་བྱ་ཚོན་གྱི་དབྱེ་བ་སོགས་མདོར་བསྡུས་སུ་བཀོད་པ་
  author: ''
  volumes:
    f42fee67399b42b8aff2bdc86d5b78f9:
      image_group_id: I1KG3636
      title: ''
      volume_number: 1
      total_pages: 40
